### ISSUE TITLE
pandas.errors.EmptyDataError: Unknown bug

### ISSUE THREAD

**Issue by seakeene** [psu-powerlab/FreqResponse#4]
Received the following error which froze the program overnight. I wasn't able to replicate it and restarting the program caused the stream to resume without interruption and function as required. Ignoring until it happens again.

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Program Files\Anaconda3\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "//khensu/Home04/seakeene/My Documents/Python Test Scripts/F-RESP Event Tool.py", line 163, in start_stream
    for i in linelist:
  File "//khensu/Home04/seakeene/My Documents/Python Test Scripts/F-RESP Event Tool.py", line 148, in process_one_file
    DL_COUNT = DL_COUNT + 1
  File "//khensu/Home04/seakeene/My Documents/Python Test Scripts/F-RESP Event Tool.py", line 48, in process_event
    # init_freq_list = init_table['STATION_1:Freq']
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Program Files\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
Attempting to reconnect to FTP
Reconnection Failed.

**Comment by seakeene** [comment]
It happened again (10/30/2019). Possible recurrence of the garbage character bug. 2019-10-30-08-58_13166. Seems to be in Slew_100 column. Hard to troubleshoot until plotting tool available.

**Comment by seakeene** [comment]
I think I fixed this when I fixed the unicode character bug. It can't be easily replicated, so we'll see. Closing for now.
